version: '3'

services:
    webapp:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - ./app:/home/appuser/app
    dev:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - ./app:/home/appuser/app
        environment:
            - FLASK_DEBUG=1
        command: python manage.py
